//
// Created by wong on 10/13/19.
//

#ifndef TRANSOCKS_WONG_TRANSPARENT_METHOD_REDIRECT_H
#define TRANSOCKS_WONG_TRANSPARENT_METHOD_REDIRECT_H

#endif //TRANSOCKS_WONG_TRANSPARENT_METHOD_REDIRECT_H
